RubyOnRails/blogging/blogger/config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'

  resources :blogs, shallow: true do
    resources :posts do
      resources :comments
    end
  end

end

RubyOnRails/blogging/blogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RubyOnRails/blogging/blogger/app/models/blog.rb
class Blog < ApplicationRecord
  has_many :posts, dependent: :destroy
end

RubyOnRails/blogging/blogger/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

RubyOnRails/blogging/blogger/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :blog
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
end

RubyOnRails/blogging/blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

RubyOnRails/blogging/blogger/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render :new
    end
  end

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to  blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:name, :description)
    end
end

RubyOnRails/blogging/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "adminpass", only: :destroy

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to  post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

RubyOnRails/blogging/blogger/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Index
  end
end

RubyOnRails/blogging/blogger/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'adminpass', except: [:index, :show]

  def index
    @blog = Blog.find(params[:blog_id])
    @posts = @blog.posts
  end

  def new
    @blog = Blog.find(params[:blog_id])
    @post = @blog.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    # post_params looks like:
    # params[:post][:id]
    # params[:post][:title]
    # params[:post][:body]
    @blog = Blog.find(params[:blog_id])
    @post = @blog.posts.create(post_params)

    if @post.save
      redirect_to @blog
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post.blog
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to @post.blog
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

RubyOnRails/blogging/blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

RubyOnRails/blogging/blogger/app/helpers/blog_helper.rb
module BlogHelper
end

RubyOnRails/blogging/blogger/app/helpers/blogs_helper.rb
module BlogsHelper
end

RubyOnRails/blogging/blogger/app/helpers/comments_helper.rb
module CommentsHelper
end

RubyOnRails/blogging/blogger/app/helpers/home_helper.rb
module HomeHelper
end

RubyOnRails/blogging/blogger/app/helpers/posts_helper.rb
module PostsHelper
end

RubyOnRails/blogging/blogger/app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <% if @blog.errors.any? %>
    <div>
      <h2>
        Please fix the following errors:
      </h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

RubyOnRails/blogging/blogger/app/views/blogs/index.html.erb
<h1>Blogs</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
  </tr>

  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.id %></td>
      <td><%= blog.name %></td>
      <td><%= blog.description %></td>
      <td><%= link_to 'Show', blog %></td>
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      <td><%= link_to 'Delete', blog,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Blog', new_blog_path %>

RubyOnRails/blogging/blogger/app/views/blogs/new.html.erb
<h1>New blog</h1>
<p>Go back to home <a href="/">page</a></p>
<p>View all <a href="/blogs">Blogs</a></p>


<%= render 'form' %>

RubyOnRails/blogging/blogger/app/views/blogs/show.html.erb
<h3>Go back to home <a href="/">page</a></h3>
<p>
  <strong>Name</strong>
  <%= @blog.name %>
</p>
<p>
  <strong>Description</strong>
  <%= @blog.description %>
</p>

<h3>View all posts</h3>
<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <%= render @blog.posts %>
</table>

<%= link_to 'New Post', new_blog_post_path(@blog)%>

RubyOnRails/blogging/blogger/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

RubyOnRails/blogging/blogger/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

RubyOnRails/blogging/blogger/app/views/home/Index.html.erb
<h1>Welcome to the page</h1>

<p>Click here to view <a href="posts">posts</a></p>

RubyOnRails/blogging/blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RubyOnRails/blogging/blogger/app/views/posts/_form.html.erb
<%= form_for([@blog, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div>
      <h2>
        Please fix the following errors:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

RubyOnRails/blogging/blogger/app/views/posts/_post.html.erb
<tr>
  <td><%= post.id %></td>
  <td><%= post.title %></td>
  <td><%= post.body %></td>
  <td><%= link_to 'Show', post_path(post) %></td>
  <td><%= link_to 'Edit', edit_post_path(post) %></td>
  <td><%= link_to 'Delete', post_path(post),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
</tr>

RubyOnRails/blogging/blogger/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

RubyOnRails/blogging/blogger/app/views/posts/index.html.erb
<h1>View Posts</h1>
<p>Go back to home <a href="/">page</a></p>
<p>Create a new <a href="/posts/new">Post</a></p>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Delete', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

RubyOnRails/blogging/blogger/app/views/posts/new.html.erb
<h1>New Post</h1>
<p>Go back to home <a href="/">page</a></p>
<p>View all <a href="/posts">Posts</a></p>


<%= render 'form' %>

RubyOnRails/blogging/blogger/app/views/posts/show.html.erb
<h3>Go back to home <a href="/">page</a></h3>
<h3>Go back to your <%= link_to 'blog' , @post.blog %></h3>
<p>
  <strong>Title</strong>
  <%= @post.title %>
</p>
<p>
  <strong>Body</strong>
  <%= @post.body %>
</p>
<h2>Comments</h2>

<%= render @post.comments %>

<h2>Add a comment:</h2>

<%= render 'comments/form' %>